Repository CapistranoIFCE/social_map, pull requests merged in 2022-09, with the labels that each got.

#13 creating map component
  SocialMap.xcodeproj/project.pbxproj
  SocialMap/Application/SocialMapApp.swift
  SocialMap/Source/View/ContentView.swift
  SocialMap/Source/View/Core/UserFeed/UserFeedController.swift
  SocialMap/Source/View/Core/UserFeed/UserFeedView.swift
  SocialMap/Source/View/General/MapView.swift
Labels: swiftUi

#14 adding and configuring user location o map
  SocialMap.xcodeproj/project.pbxproj
  SocialMap/Source/View/Core/UserFeed/ MockedPinView.swift
  SocialMap/Source/View/Core/UserFeed/UserFeedController.swift
  SocialMap/Source/View/Core/UserFeed/UserFeedView.swift
  SocialMap/Source/View/General/MapView.swift
Labels: enhancement, swiftUi

#15 delightful experience of walking on the map
  SocialMap.xcodeproj/project.pbxproj
  SocialMap/Source/Enum/MediaTypeEnum.swift
  SocialMap/Source/Model/UserStoryModel.swift
  SocialMap/Source/View/Core/UserFeed/UserFeedController.swift
  SocialMap/Source/View/Core/UserFeed/UserFeedView.swift
  SocialMap/Source/View/General/Coordinators/MapViewCoordinator.swift
  SocialMap/Source/View/General/LandmarkAnnotation.swift
  SocialMap/Source/View/General/MapView.swift
Labels: enhancement, animation, swiftUi

#17 Adicionado o Photo Image Picker no projeto Social Map.
  SocialMap.xcodeproj/project.pbxproj
  SocialMap/Source/View/Core/UserFeed/UserFeedController.swift
  SocialMap/Source/View/Core/UserFeed/UserFeedView.swift
  SocialMap/Source/View/Core/UserFeed/UserMapLocation.swift
  SocialMap/Source/View/General/Coordinators/PhotoPickerCoordinator.swift
  SocialMap/Source/View/General/ImagePicker.swift
  SocialMap/Source/View/General/MapView.swift
Labels: enhancement, swiftUi

#19 16 refactor user walking on map to go for the near photo
  SocialMap.xcodeproj/project.pbxproj
  SocialMap/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  SocialMap/Source/.DS_Store
  SocialMap/Source/Enum/DeviceSideEnum.swift
  SocialMap/Source/View/.DS_Store
  SocialMap/Source/View/Core/UserFeed/UserFeedController.swift
  SocialMap/Source/View/Core/UserFeed/UserFeedView.swift
  SocialMapTests/SocialMapTests.swift
  SocialMapTests/UserFeedController/UserFeedControllerTest.swift
Labels: enhancement, animation, swiftUi

#21 18 user image story no feed view
  SocialMap.xcodeproj/project.pbxproj
  SocialMap/.DS_Store
  SocialMap/Resources/Assets.xcassets/friends_laughing.imageset/Contents.json
  SocialMap/Resources/Assets.xcassets/friends_laughing.imageset/friends_laughing.jpg
  SocialMap/Resources/Assets.xcassets/friends_sunset.imageset/Contents.json
  SocialMap/Resources/Assets.xcassets/friends_sunset.imageset/friends_sunset.jpg
  SocialMap/Resources/Assets.xcassets/mountain.imageset/Contents.json
  SocialMap/Resources/Assets.xcassets/mountain.imageset/mountain.jpg
  SocialMap/Resources/Assets.xcassets/sunset_beach.imageset/Contents.json
  SocialMap/Resources/Assets.xcassets/sunset_beach.imageset/sunset_beach.png
  SocialMap/Resources/Assets.xcassets/three_friends_laughing.imageset/Contents.json
  SocialMap/Resources/Assets.xcassets/three_friends_laughing.imageset/three_friends_laughing.jpg
  SocialMap/Source/View/Core/UserFeed/UserComponentStory.swift
  SocialMap/Source/View/Core/UserFeed/UserFeedController.swift
  SocialMap/Source/View/Core/UserFeed/UserFeedView.swift
  SocialMap/Source/View/Core/UserStoriesView.swift
  SocialMap/Source/View/General/Coordinators/MapViewCoordinator.swift
  SocialMap/Source/View/General/MapView.swift
Labels: enhancement, swiftUi

#22 5 delightful animation of reallocate image pin on map
  SocialMap.xcodeproj/project.pbxproj
  SocialMap/Resources/Lottie/pulse.json
  SocialMap/Source/Model/UserStoryModel.swift
  SocialMap/Source/View/Core/UserFeed/UserFeedController.swift
  SocialMap/Source/View/Core/UserFeed/UserFeedView.swift
  SocialMap/Source/View/General/Coordinators/MapViewCoordinator.swift
  SocialMap/Source/View/General/Coordinators/PhotoPickerCoordinator.swift
  SocialMap/Source/View/General/CustomGestureRecognizer.swift
  SocialMap/Source/View/General/ImagePicker.swift
  SocialMap/Source/View/General/LottieView.swift
  SocialMap/Source/View/General/MapView.swift
  SocialMap/Source/View/General/UserImageAnnotation.swift
  SocialMapTests/UserFeedController/UserFeedControllerTest.swift
Labels: enhancement, animation, swiftUi

#25 9 visualize images on initial screen map screen
  .DS_Store
  SocialMap.xcodeproj/project.pbxproj
  SocialMap/Resources/.DS_Store
  SocialMap/Resources/Assets.xcassets/.DS_Store
  SocialMap/Resources/Lottie/pulse.json
  SocialMap/Source/Extension/UIImageExtension.swift
  SocialMap/Source/View/Core/UserFeed/UserComponentStory.swift
  SocialMap/Source/View/Core/UserFeed/UserFeedController.swift
  SocialMap/Source/View/Core/UserFeed/UserFeedView.swift
  SocialMap/Source/View/General/Coordinators/MapViewCoordinator.swift
  SocialMap/Source/View/General/Coordinators/PhotoPickerCoordinator.swift
  SocialMap/Source/View/General/ImagePicker.swift
  SocialMap/Source/View/General/MapView.swift
  SocialMap/Source/View/General/UserImageAnnotation.swift
Labels: enhancement, swiftUi

#29 add a new flow to user register the photograpy
  .DS_Store
  PicMap.xcodeproj/project.pbxproj
  SocialMap/Source/View/Core/UserFeed/UserFeedController.swift
  SocialMap/Source/View/Core/UserFeed/UserFeedView.swift
  SocialMap/Source/View/General/Coordinators/PhotoPickerCoordinator.swift
Labels: enhancement, animation, swiftUi
